FROM rust:1.85.0

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    clang \
    llvm \
    musl-tools \
    && rm -rf /var/lib/apt/lists/*

# Set up for cross-compilation
RUN rustup target add aarch64-unknown-linux-musl

WORKDIR /app

# Copy the entire project and build
ENTRYPOINT ["bash", "-c"]
CMD ["cargo build --target aarch64-unknown-linux-musl"] 