import {
  LucideProps,
  Moon,
  SunMedium,
  Laptop,
  Chrome,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Command,
  Plus,
  Brain,
  MessageSquare,
  Settings,
  BarChart,
  BookOpen,
  Home,
  RefreshCw,
  AlertTriangle,
} from "lucide-react";

export type Icon = LucideProps;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  google: Chrome,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  command: Command,
  plus: Plus,
  brain: Brain,
  messageSquare: MessageSquare,
  settings: Settings,
  barChart: BarChart,
  bookOpen: BookOpen,
  home: Home,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
};
