import {
  LucideProps,
  Moon,
  SunMedium,
  Laptop,
  Chrome,
  Loader2,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Command,
  Plus,
  Brain,
  MessageSquare,
  Settings,
  BarChart,
  BookOpen,
  Home,
  RefreshCw,
  AlertTriangle,
  TrendingUp,
  TrendingDown,
  Minus,
  FileText,
  Flame,
  Edit,
  Hash,
  List,
  Sparkles,
  Calendar,
  Heart,
  Lightbulb,
  Zap,
  Shuffle,
  X,
  Download,
  Share,
  Trash2,
  Bell,
  BellRing,
  Monitor,
  Eye,
  EyeOff,
  Grid,
  LayoutList,
  CalendarDays,
  Shield,
  User,
  LogOut,
  Check,
} from "lucide-react";

export type Icon = LucideProps;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  google: Chrome,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  command: Command,
  plus: Plus,
  brain: Brain,
  messageSquare: MessageSquare,
  settings: Settings,
  barChart: BarChart,
  bookOpen: BookOpen,
  home: Home,
  refresh: RefreshCw,
  alertTriangle: AlertTriangle,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  minus: Minus,
  fileText: FileText,
  flame: Flame,
  edit: Edit,
  hash: Hash,
  list: List,
  sparkles: Sparkles,
  calendar: Calendar,
  heart: Heart,
  lightbulb: Lightbulb,
  zap: Zap,
  shuffle: Shuffle,
  x: X,
  download: Download,
  share: Share,
  trash: Trash2,
  bell: Bell,
  bellRing: BellRing,
  monitor: Monitor,
  eye: Eye,
  eyeOff: EyeOff,
  grid: Grid,
  layoutList: LayoutList,
  calendarDays: CalendarDays,
  shield: Shield,
  user: User,
  logOut: LogOut,
  check: Check,
};
