[build]
rustflags = []

[env]
# Empty default environment

# ARM specific settings - simplified for OpenSSL
[target.aarch64-unknown-linux-musl]
rustflags = []
# Use rust-lld for linking
env = { "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS" = "-Clink-self-contained=yes -Clinker=rust-lld" }

# x86_64 specific settings - disable AVX512
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=-avx512f"]
env = { "CFLAGS" = "-mno-avx512f" }
